export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const LOGIN_FACEBOOK_CANCELLED = 'LOGIN_FACEBOOK_CANCELLED'
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR'

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR'

export const POST_THING_REQUEST = 'POST_THING_REQUEST'
export const POST_THING_SUCCESS = 'POST_THING_SUCCESS'
export const POST_THING_ERROR = 'POST_THING_ERROR'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'
