export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const LOGIN_FACEBOOK_CANCELLED = 'LOGIN_FACEBOOK_CANCELLED'
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR'

export const AUTH_USER = 'AUTH_USER'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR'

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_ERROR = 'FETCH_USER_PROFILE_ERROR'

export const POST_NEW_THING_REQUEST = 'POST_NEW_THING_REQUEST'
export const POST_NEW_THING_SUCCESS = 'POST_NEW_THING_SUCCESS'
export const POST_NEW_THING_ERROR = 'POST_NEW_THING_ERROR'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'
