export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const LOGIN_FACEBOOK_CANCELLED = 'LOGIN_FACEBOOK_CANCELLED'
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR'

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR'
