export const POST_THING_REQUEST = 'POST_THING_REQUEST'
export const POST_THING_SUCCESS = 'POST_THING_SUCCESS'
export const POST_THING_ERROR = 'POST_THING_ERROR'

export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'
